remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # theme: jekyll-theme-NAME


title: [The Goonies 1986]
description: [Tribute to the classic MSX game by RetroRevolve]

show_downloads: [false]

